version: '3.8'

services:
  drupal:
    build:
      context: .
      args:
        - USER_ID=${UID:-1000}
    image: drupal-custom
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - drupal-files:/var/www/html/web/sites/default/files
      - drupal-config:/var/www/html/config/sync
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: drupal
      DB_USER: drupal
      DB_PASSWORD: drupal
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db

volumes:
  db_data:
  drupal-files:
  drupal-config:
